"""
MedPredict AI - PDF Report Generation (Phase 6)
Generates professional patient report PDFs using ReportLab.
"""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# Brand colors
BRAND_BLUE = colors.HexColor("#1a73e8")
BRAND_GREEN = colors.HexColor("#34a853")
BRAND_RED = colors.HexColor("#ea4335")
LIGHT_GRAY = colors.HexColor("#f8f9fa")
DARK_GRAY = colors.HexColor("#343a40")
MED_GRAY = colors.HexColor("#6c757d")


def generate_report(
    symptoms: list[str],
    top_prediction: dict,
    top3: list[dict],
    shap_factors: list[dict],
    patient_name: str = "Patient",
) -> bytes:
    """
    Generate a professional PDF medical report.
    Returns PDF as bytes for download.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Header ─────────────────────────────────────────────────────────────────
    header_style = ParagraphStyle(
        "Header", fontSize=22, textColor=BRAND_BLUE,
        alignment=TA_CENTER, fontName="Helvetica-Bold", spaceAfter=4
    )
    sub_style = ParagraphStyle(
        "Sub", fontSize=10, textColor=MED_GRAY,
        alignment=TA_CENTER, spaceAfter=2
    )
    story.append(Paragraph("🏥 MedPredict AI", header_style))
    story.append(Paragraph("AI-Powered Disease Prediction Report", sub_style))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", sub_style))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_BLUE, spaceAfter=16))

    # ── Disclaimer ─────────────────────────────────────────────────────────────
    disclaimer_style = ParagraphStyle(
        "Disclaimer", fontSize=8, textColor=colors.red,
        alignment=TA_CENTER, backColor=colors.HexColor("#fff3f3"),
        borderPadding=8, spaceAfter=16
    )
    story.append(Paragraph(
        "⚠️ DISCLAIMER: This report is generated by an AI system and is NOT a substitute for "
        "professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider.",
        disclaimer_style
    ))

    # ── Patient Info ───────────────────────────────────────────────────────────
    section_title = ParagraphStyle(
        "SectionTitle", fontSize=13, textColor=BRAND_BLUE,
        fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=8
    )
    normal = ParagraphStyle("Normal2", fontSize=10, textColor=DARK_GRAY, spaceAfter=4)

    story.append(Paragraph("Patient Information", section_title))
    patient_data = [
        ["Patient Name:", patient_name],
        ["Report Date:", datetime.now().strftime("%Y-%m-%d")],
        ["Report ID:", f"MPA-{datetime.now().strftime('%Y%m%d%H%M%S')}"],
    ]
    pt = Table(patient_data, colWidths=[5*cm, 10*cm])
    pt.setStyle(TableStyle([
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
        ("TEXTCOLOR", (0,0), (-1,-1), DARK_GRAY),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
    ]))
    story.append(pt)

    # ── Symptoms ───────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6"), spaceBefore=12, spaceAfter=12))
    story.append(Paragraph("Reported Symptoms", section_title))
    symptom_text = " • ".join([s.replace("_", " ").title() for s in symptoms])
    story.append(Paragraph(f"• {chr(10).join(['• ' + s.replace('_', ' ').title() for s in symptoms])}", normal))

    # ── Primary Prediction ─────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6"), spaceBefore=12, spaceAfter=12))
    story.append(Paragraph("Primary Diagnosis Prediction", section_title))

    conf = top_prediction["confidence_pct"]
    conf_color = BRAND_GREEN if conf >= 70 else (colors.orange if conf >= 50 else BRAND_RED)
    margin = top3[0]["confidence_pct"] - top3[1]["confidence_pct"]
    uncertainty = 100 - conf

    pred_data = [
        ["Predicted Disease", top_prediction["disease"]],
        ["Confidence Score (calibrated)", f"{conf}%"],
        ["Margin over 2nd choice", f"{margin:.1f} pts"],
        ["Uncertainty", f"{uncertainty:.1f}%"],
        ["Recommended Specialist", top_prediction["doctor"]],
    ]
    pred_table = Table(pred_data, colWidths=[6*cm, 10*cm])
    pred_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), BRAND_BLUE),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("BACKGROUND", (0,1), (-1,1), LIGHT_GRAY),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
        ("TEXTCOLOR", (0,0), (-1,-1), DARK_GRAY),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
        ("ROWBACKGROUNDS", (0,0), (-1,-1), [colors.white, LIGHT_GRAY]),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
    ]))
    story.append(pred_table)
    story.append(Paragraph(
        "Confidence is a calibrated model probability, not diagnostic certainty.",
        ParagraphStyle("note2", fontSize=8, textColor=MED_GRAY, spaceBefore=4)
    ))

    # ── Top 3 Predictions ──────────────────────────────────────────────────────
    story.append(Spacer(1, 12))
    story.append(Paragraph("Differential Diagnosis (Top 3)", section_title))

    top3_data = [["Rank", "Disease", "Confidence", "Specialist"]]
    for i, pred in enumerate(top3, 1):
        top3_data.append([
            f"#{i}",
            pred["disease"],
            f"{pred['confidence_pct']}%",
            pred["doctor"],
        ])

    top3_table = Table(top3_data, colWidths=[1.5*cm, 5*cm, 3*cm, 6.5*cm])
    top3_table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), DARK_GRAY),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("TEXTCOLOR", (1,0), (-1,-1), DARK_GRAY),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING", (0,0), (-1,-1), 8),
        ("LEFTPADDING", (0,0), (-1,-1), 8),
        ("ALIGN", (0,0), (0,-1), "CENTER"),
        ("ALIGN", (2,0), (2,-1), "CENTER"),
    ]))
    story.append(top3_table)

    # ── SHAP Explanation ───────────────────────────────────────────────────────
    if shap_factors:
        story.append(Spacer(1, 12))
        story.append(Paragraph("AI Explainability — Key Factors", section_title))
        story.append(Paragraph(
            "SHAP impact scores (not probabilities) of the symptoms with the greatest "
            "influence on the AI's prediction. Positive values push toward the predicted "
            "disease; negative values push away from it.",
            ParagraphStyle("note", fontSize=9, textColor=MED_GRAY, spaceAfter=8)
        ))

        shap_data = [["Symptom", "Impact", "Direction", "Strength"]]
        for f in shap_factors[:6]:
            shap_data.append([
                f["symptom"],
                f["impact_label"],
                f["direction"],
                f["strength"],
            ])

        shap_table = Table(shap_data, colWidths=[6*cm, 3*cm, 4*cm, 3*cm])
        shap_table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#6f42c1")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#dee2e6")),
            ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
            ("BOTTOMPADDING", (0,0), (-1,-1), 8),
            ("TOPPADDING", (0,0), (-1,-1), 8),
            ("LEFTPADDING", (0,0), (-1,-1), 8),
            ("ALIGN", (1,0), (3,-1), "CENTER"),
        ]))
        story.append(shap_table)

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=BRAND_BLUE))
    story.append(Paragraph(
        "MedPredict AI | For educational and informational purposes only | Not for clinical use",
        ParagraphStyle("footer", fontSize=8, textColor=MED_GRAY, alignment=TA_CENTER, spaceBefore=8)
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


if __name__ == "__main__":
    pdf = generate_report(
        symptoms=["fever", "cough", "headache"],
        top_prediction={"disease": "Influenza", "confidence_pct": 91.0, "doctor": "General Physician"},
        top3=[
            {"disease": "Influenza", "confidence_pct": 91.0, "doctor": "General Physician"},
            {"disease": "COVID-19", "confidence_pct": 84.0, "doctor": "Infectious Disease Specialist"},
            {"disease": "Pneumonia", "confidence_pct": 71.0, "doctor": "Pulmonologist"},
        ],
        shap_factors=[
            {
                "symptom": "Fever",
                "impact_label": "+0.137",
                "strength": "Strong",
                "present": True,
                "direction": "Supports prediction",
            },
        ],
        patient_name="Test Patient",
    )
    with open("/tmp/test_report.pdf", "wb") as f:
        f.write(pdf)
    print(f"PDF generated: {len(pdf)} bytes")
